// Fill out your copyright notice in the Description page of Project Settings.


#include "Vertexes/M2ActionVertex.h"

void UM2ActionVertex::ExecuteTriggerOnPatch(FName TriggerName)
{
	FName UberGraphTriggerName = Cast<UM2MetasoundLiteralPin>(InputM2SoundPins[TriggerName])->AutoGeneratedGraphInputName;
	
	GetSequencerData()->ExecuteTriggerParameter(UberGraphTriggerName);
}
